### PR TITLE
Add APBPrescTable global variable

### PR DESCRIPTION
**Pull request by mbohdal**
This is required by the HAL drivers to properly calculate APB1 and APB2 clocks.
Used for example when starting I2C device via HAL_I2C_Init().

### CODE REVIEW

**Comment by mbohdal** [comment]
@KamilSzczygiel do You think we should also add this?
`const uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9};`
I think this one is not necessary to setup any HAL drivers, just the main clock or AHB in the HAL_RCC, but that is already handled by distortos.

**Comment by FreddieChopin** [comment]
Hello and thanks for another contribution! Good to know that you are still using distortos (;

I have just one request - could we move this new array into a new file, called `APBPrescTable.cpp`?

As for your question:
> I think this one is not necessary to setup any HAL drivers, just the main clock or AHB in the HAL_RCC, but that is already handled by distortos.

If nothing requires it (the linking succeeds, there's no error about undefined reference), then I don't think we should add such array.

**Comment by mbohdal** [comment]
> I have just one request - could we move this new array into a new file, called `APBPrescTable.cpp`?
Not a problem, I will prepare a new commit shortly
> 
> As for your question:
> 
> > I think this one is not necessary to setup any HAL drivers, just the main clock or AHB in the HAL_RCC, but that is already handled by distortos.
> 
> If nothing requires it (the linking succeeds, there's no error about undefined reference), then I don't think we should add such array.
Yes, it is not needed, compilation and linking succeeds without this.

**Comment by FreddieChopin** [comment]
Done! I've merged your commit with a few minor changes - hope that it's OK.

Thanks for your contribution! Keep them coming (;

**Pull request closed without merging**
